import { platform, addCollection, saveRecord, saveSchema, saveRoute, workflowTrace, validateConnection, validateListing, themeFor } from './capabilities.mjs';

export function capabilityUI(ctx) {
  const { getProject: project, getDB: db, ui, esc, btn, icon, dialog, closeModal, render, save, toast, commit, act, themes, answer, recordRun, startProject, requireAccount } = ctx;
  const s = { data: 'sources', collection: 'feedback', schema: false, market: 'All', marketQuery: '', query: '', designScope: 'All', selectedTheme: '', trace: null };
  const val = id => document.getElementById(id)?.value.trim() || '';
  const field = (id, label, value = '', attrs = '') => `<div class="field"><label class="field-label" for="${id}">${label}</label><input id="${id}" value="${esc(value)}" ${attrs}></div>`;
  const select = (id, label, items, value) => `<div class="field"><label class="field-label" for="${id}">${label}</label><select id="${id}">${items.map(x => { const [v,l] = Array.isArray(x) ? x : [x,x]; return `<option value="${esc(v)}" ${v === value ? 'selected' : ''}>${esc(l)}</option>`; }).join('')}</select></div>`;
  const check = (id, label, checked) => `<label class="check-label"><input id="${id}" type="checkbox" ${checked ? 'checked' : ''}>${label}</label>`;
  const checked = id => !!document.getElementById(id)?.checked;
  const submit = (label, cancel = true) => `<p class="form-error" id="cap-error" role="alert"></p><div class="dlg-actions">${cancel ? btn('Cancel', 'close') : ''}<button type="submit" class="btn primary">${label}</button></div>`;
  const form = (id, body, label) => `<form id="cap-${id}" class="stack">${body}${submit(label)}</form>`;
  const title = (name, desc, actions = '') => `<div class="cap-heading"><div><h2>${name}</h2><p class="muted">${desc}</p></div><div class="row wrap">${actions}</div></div>`;
  const change = (reason, fn) => { commit(reason, fn); s.trace = null; };
  const agentName = id => id === 'main' ? ctx.archetype(project()).agent.name : project().agents?.find(a => a.id === id)?.name || 'Removed agent';
  const agentChoices = () => [['main', agentName('main')], ...(project().agents || []).map(a => [a.id, a.name])];
  function navData() {
    return `<div class="cap-nav" role="tablist" aria-label="Data views">${[['sources','Knowledge'],['database','Database'],['auth','App users']].map(([k,l]) => btn(l,'cap-data',`chip ${s.data === k ? 'on' : ''}`,`data-view="${k}" role="tab" aria-selected="${s.data === k}"`)).join('')}</div>`;
  }
  function dataPane() {
    const p = project(), st = platform(p);
    if (s.data === 'sources') return '';
    if (s.data === 'auth') return `<div class="cap-scroll">${navData()}${title('App users', 'Control how people enter the app you are building.')}
      <div class="two"><form id="cap-auth" class="card stack"><h3>Sign-in and sessions</h3>${select('cap-provider','Sign-in provider',['Email','Google','GitHub'], st.auth.provider)}${check('cap-required','Require sign-in to use the app', p.settings.audience === 'team')}${check('cap-signup','Allow new people to create an account', st.auth.signup)}${select('cap-session','Session duration', [['1','1 hour'],['24','24 hours'],['168','7 days']], String(st.auth.sessionHours))}${submit('Save access settings', false)}</form>
      <div class="card"><h3>Test the experience</h3><p class="muted" style="margin:10px 0">Walk through sign-in, account creation and an expired session. These are demo identities; no credentials are collected.</p><div class="stack">${btn('Preview sign-in','cap-auth-preview','btn')}${btn('Preview expired session','cap-auth-expired','btn')}</div><hr><h3>Demo app users</h3><div class="listrow"><span>alex@example.com<br><small class="muted">Sample account</small></span><span class="status">Member</span></div><p class="hint">Access settings describe the intended production behavior. Browser-local demo links are not an access-control boundary.</p></div></div></div>`;
    const c = st.collections.find(c => c.name === s.collection) || st.collections[0];
    s.collection = c.name;
    const rows = c.records.filter(r => JSON.stringify(r).toLowerCase().includes(s.query.toLowerCase()));
    return `<div class="cap-scroll">${navData()}${title('Database', 'Collections, records and schema saved with this project.', btn('New collection','cap-collection-new','btn primary sm'))}<div class="database-layout"><aside class="collection-list" aria-label="Collections">${st.collections.map(x => btn(`<span>${icon('db',14)} ${esc(x.name)}</span><small>${x.records.length}</small>`,'cap-collection',`collection ${x.name === c.name ? 'on' : ''}`,`data-name="${esc(x.name)}"`)).join('')}<p class="hint">Browser-local data<br>Included in source export and version history.</p></aside><section class="database-main"><div class="row between wrap"><h3>${esc(c.name)}</h3><div class="row">${btn(s.schema ? 'View records' : 'View schema','cap-schema-toggle','btn sm')}${btn(s.schema ? 'Edit schema' : 'Add record',s.schema ? 'cap-schema-edit' : 'cap-record-new','btn primary sm')}</div></div>
      ${s.schema ? `<div class="table-scroll"><table class="cap-table"><thead><tr><th>Field</th><th>Type</th><th>Required</th></tr></thead><tbody><tr><td>id</td><td>UUID</td><td>Generated</td></tr>${c.fields.map(f => `<tr><td>${esc(f.name)}</td><td>${esc(f.type)}</td><td>${f.required ? 'Yes' : 'No'}</td></tr>`).join('')}</tbody></table></div><p class="hint">Schema changes are checked against every saved record before they are applied.</p>` : `<form id="cap-search-records" class="row" style="margin:16px 0">${field('cap-record-query','Find records',s.query)}<button class="btn sm" type="submit">Search</button></form>${rows.length ? `<div class="table-scroll"><table class="cap-table"><thead><tr>${c.fields.map(f=>`<th>${esc(f.name)}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${rows.map(r=>`<tr>${c.fields.map(f=>`<td>${esc(String(r[f.name] ?? '—'))}</td>`).join('')}<td>${btn('Edit','cap-record-edit','btn sm quiet',`data-id="${r.id}"`)}${btn('Delete','cap-record-delete','btn sm quiet',`data-id="${r.id}"`)}</td></tr>`).join('')}</tbody></table></div>` : `<div class="empty"><h3>${s.query ? 'No matching records' : 'Your collection is ready'}</h3><p>${s.query ? 'Try another search, or clear the search field.' : 'Add a record to see how the app stores its data.'}</p></div>`}`}</section></div></div>`;
  }
  function workflowPane() {
    const p = project(), st = platform(p), agents = p.agents || [];
    const routes = st.routingConfigured ? st.routes : agents.map(a=>({from:'main',to:a.id,when:/no answer/i.test(a.trigger)?'unanswered':/on request/i.test(a.trigger)?'manual':'always', implicit:true}));
    const node = (id, name, sub, cls='') => `<button type="button" class="flow-node ${cls}" data-action="cap-node" data-id="${id}"><span class="node-icon">${icon('bot',19)}</span><strong>${esc(name)}</strong><small>${esc(sub)}</small><span class="node-open">Configure ${icon('arrow',13)}</span></button>`;
    return `<div class="workflow-pane"><div class="workflow-head">${title('Agent workflow', 'Follow the work from a user’s question to the answer.', btn('Connections','cap-connections','btn sm') + btn('Add agent','add-agent','btn primary sm'))}<div class="row wrap"><span class="status">${st.architecture === 'managed' ? 'Managed in Lyzr Studio' : 'Owned by your repository'}</span>${btn('Architecture','cap-architecture','link')}${btn('Advanced settings','cap-advanced','link')}</div></div>
      <div class="workflow-map" aria-label="Agent workflow graph"><div class="flow-end">${icon('message',15)} User asks a question</div><div class="flow-wire"></div>${node('main',agentName('main'),p.settings.framework,'main-node')}<div class="flow-wire"></div><div class="flow-source">${icon('book',14)} Reads ${esc(p.sourceName)} · ${(p.tools || ['read_source']).includes('read_source') ? 'Allowed' : 'Access disabled'}</div>
      ${agents.length ? `<div class="flow-wire"></div><div class="flow-branches">${agents.map(a=>`<div class="flow-branch"><span class="flow-condition">${esc(routes.filter(r=>r.to===a.id).map(r=>`${agentName(r.from)} → ${r.when === 'unanswered' ? 'No answer' : r.when === 'answered' ? 'Answer found' : r.when === 'manual' ? 'On request' : 'Always'}`).join(', ') || 'Not connected')}</span>${node(a.id,a.name,a.enabled === false ? 'Paused' : a.responsibility)}</div>`).join('')}</div>` : `<div class="flow-wire"></div>${btn(`${icon('plus',14)} Add a specialist or handoff`, 'add-agent','flow-add')}`}
      <div class="flow-wire"></div><div class="flow-end">${icon('check',15)} Return to the app</div></div>
      <div class="workflow-bottom"><section class="card"><div class="row between"><h3>Handoffs</h3>${btn('Connect agents','cap-route-new','btn sm',agents.length ? '' : 'disabled')}</div>${routes.length ? routes.map(r=>`<div class="listrow"><div><strong>${esc(agentName(r.from))} → ${esc(agentName(r.to))}</strong><p>${esc(r.when)}${r.implicit ? ' · from agent trigger' : ''}</p></div>${r.id ? btn('Remove','cap-route-delete','btn sm quiet',`data-id="${r.id}"`) : ''}</div>`).join('') : '<p class="muted" style="margin-top:10px">One agent handles the whole request. Add another when the work needs a specialist.</p>'}</section>
      <section class="card"><h3>Test workflow</h3><p class="hint">The main agent answers locally; other nodes simulate the route without calling services.</p><form id="cap-workflow-test" class="row" style="margin-top:12px"><label class="sr" for="cap-workflow-input">Workflow input</label><input id="cap-workflow-input" value="${esc(s.trace?.input || p.chips[0][1])}" required><button class="btn primary sm" type="submit">Run workflow</button></form>${s.trace ? `<ol class="trace">${s.trace.nodes.map(n=>`<li><strong>${esc(n.name)}</strong> · ${esc(n.status)}${n.condition ? ` (${esc(n.condition)})` : ''}</li>`).join('')}</ol><p class="out">${esc(s.trace.output)}</p>` : ''}</section></div></div>`;
  }
  function collectionForm(edit = false) {
    const c = platform(project()).collections.find(c=>c.name === s.collection);
    const fields = edit ? c.fields : [{name:'title',type:'string',required:true}];
    dialog(edit ? `Schema · ${esc(c.name)}` : 'Create a collection', 'Define fields using JSON. Types: string, number or boolean. Every record also gets a unique id.',form('schema', `${edit ? `<input type="hidden" id="cap-schema-editing" value="${esc(c.name)}">` : field('cap-collection-name','Collection name','','required placeholder="requests"')}<label class="field-label" for="cap-fields">Fields</label><textarea id="cap-fields" rows="9" class="mono" required>${esc(JSON.stringify(fields,null,2))}</textarea>`, edit ? 'Save schema' : 'Create collection'));
  }
  function recordForm(id = '') {
    const c = platform(project()).collections.find(c=>c.name === s.collection);
    const row = c.records.find(r=>r.id===id);
    const value = row ? Object.fromEntries(Object.entries(row).filter(([k])=>k!=='id')) : Object.fromEntries(c.fields.map(f=>[f.name,f.type==='boolean'?false:f.type==='number'?0:'']));
    dialog(id ? 'Edit record' : 'Add a record', `Collection: ${esc(c.name)}`,form('record',`<input type="hidden" id="cap-record-id" value="${id}"><label for="cap-record-json" class="field-label">Record JSON</label><textarea id="cap-record-json" rows="9" class="mono" required>${esc(JSON.stringify(value,null,2))}</textarea>`, 'Save record'));
  }
  function routeDialog() {
    dialog('Connect agents','Choose when work moves to another agent. Your first saved handoff replaces the suggested routes; add each connection you need. Loops are checked before saving.',form('route',select('cap-from','From',agentChoices(),'main')+select('cap-to','To',agentChoices().filter(([id])=>id!=='main'),project().agents?.[0]?.id)+select('cap-when','When',[['always','Always'],['answered','An answer is found'],['unanswered','No answer is found']],'always'),'Save handoff'));
  }
  function editAgent(id) {
    if (id === 'main') { ui.agentSel='main'; ui.agentTab='behavior'; return render(); }
    const a = project().agents.find(a=>a.id===id);
    dialog(esc(a.name),'Configuration is saved with the app. Execution of this extra agent is simulated.',form('agent',`<input id="cap-agent-id" type="hidden" value="${a.id}">${field('cap-agent-name','Name',a.name,'required')}${field('cap-agent-job','Responsibility',a.responsibility,'required')}<label class="field-label" for="cap-agent-instructions">Instructions</label><textarea id="cap-agent-instructions" rows="4">${esc(a.instructions || a.responsibility)}</textarea>${select('cap-agent-framework','Framework',['Lyzr managed','LangGraph','CrewAI','OpenAI Agents SDK','Custom framework'],a.framework || project().settings.framework)}${field('cap-agent-entry','Entry point or Studio agent ID',a.entry || a.studioId || '')}${check('cap-agent-enabled','Enable this agent',a.enabled !== false)}${a.origin?.includes('Studio') ? `<p class="hint">${esc(a.origin)}. This prototype edits a local app copy.</p><a href="https://studio.lyzr.ai/" target="_blank" rel="noopener">Open Lyzr Studio</a>` : ''}`,'Save agent'),btn('Duplicate agent','cap-agent-duplicate','btn sm',`data-id="${id}"`)+btn('Remove agent','remove-agent','btn danger sm',`data-id="${id}"`));
  }
  function connections() {
    const all = platform(project()).connections;
    dialog('Connections','Choose the resources each agent can access. Connection tests and actions are simulated.',`<div class="row wrap" style="margin-bottom:18px">${['MCP','OpenAPI','A2A'].map(k=>btn(`Add ${k}`,'cap-connection-new','btn',`data-kind="${k}"`)).join('')}</div>${all.length ? all.map(c=>`<div class="card"><div class="row between"><div><h3>${esc(c.name)}</h3><p class="hint">${esc(c.kind)} · ${esc(c.status)} · ${esc(agentName(c.agent))}</p></div>${btn('Configure','cap-connection-edit','btn sm',`data-id="${c.id}"`)}</div><p style="margin-top:8px">${esc(c.scope)} · ${esc(c.actions.join(', '))}</p><div class="row wrap" style="margin-top:12px">${btn('Test connection','cap-connection-test','btn sm',`data-id="${c.id}"`)}${btn('Disconnect','cap-connection-remove','btn sm quiet',`data-id="${c.id}"`)}</div></div>`).join('') : '<div class="empty"><h3>Give agents the right tools</h3><p>Connect an MCP server, an API, or an external agent. Review permissions before enabling it.</p></div>'}`,'',{wide:true});
  }
  function connectionForm(kind, id = '') {
    const c = platform(project()).connections.find(c=>c.id===id) || {kind,actions:['read'],agent:'main',scope:''};
    dialog(`${id ? 'Configure' : 'Connect'} ${c.kind}`, 'Use an example endpoint. No network requests are made; never paste secrets.',form('connection',`<input type="hidden" id="cap-connection-id" value="${id}"><input type="hidden" id="cap-connection-kind" value="${esc(c.kind)}">${field('cap-connection-name','Connection name',c.name || '','required placeholder="Support tools"')}${field('cap-endpoint','HTTPS endpoint',c.endpoint || '', 'required type="url" placeholder="https://tools.example.com/mcp"')}${field('cap-scope','Allowed resource',c.scope,'required placeholder="Support tickets only"')}${select('cap-connection-agent','Agent',agentChoices(),c.agent)}${select('cap-connection-auth','Authentication',['Environment variable','OAuth'],c.auth || 'Environment variable')}${field('cap-connection-env','Credential variable name',c.env || 'TOOLS_API_KEY','pattern="[A-Z][A-Z0-9_]*"')}<span class="field-label">Permitted actions</span><div class="row wrap">${['read','write','execute'].map(a=>check(`cap-action-${a}`,a,c.actions.includes(a))).join('')}</div>${check('cap-connection-approval','Ask a person before write or execute actions',c.approval !== false)}`,'Save connection'));
  }
  const marketItems = [
    { name:'Policy desk', category:'HR', use:'Answer questions', summary:'Answer employee policy questions with sources and a human handoff.', prompt:'Build a policy assistant for our team with sources and feedback buttons', agents:['Handbook assistant (answers or hands off)'], theme:'forest' },
    { name:'Inbox triage', category:'Support', use:'Route requests', summary:'Route requests to billing, access or engineering with a clear priority.', prompt:'Build a support inbox that routes customer requests and drafts a reply', agents:['Request sorter (routes and drafts)'], theme:'ocean' },
    { name:'Revenue lens', category:'Analytics', use:'Analyze data', summary:'Ask questions about regional revenue and inspect the supporting numbers.', prompt:'Build a sales dashboard to compare revenue and explain growth', agents:['Data analyst'], theme:'plum' },
  ];
  function library() {
    const items = marketItems.filter(x=>(s.market==='All'||x.category===s.market) && `${x.name} ${x.summary} ${x.use}`.toLowerCase().includes(s.marketQuery.toLowerCase()));
    const published = db().projects.map(p=>p.releases.at(-1)).filter(r=>r?.platform?.marketplace?.enabled && (s.market==='All'||r.platform.marketplace.category===s.market) && `${r.name} ${r.platform.marketplace.summary} ${r.platform.marketplace.tags.join(' ')}`.toLowerCase().includes(s.marketQuery.toLowerCase()));
    dialog('Explore agentlets','Curated example apps. Preview the experience and inspect the agents before starting your own.',`<form id="cap-market-search" class="row" style="margin-bottom:16px">${field("cap-market-query","Search apps or use cases",s.marketQuery)}<button class="btn sm" type="submit">Search</button></form><div class="row wrap" style="margin-bottom:18px">${['All','Productivity','HR','Support','Analytics','Finance','Marketing'].map(x=>btn(x,'cap-market-filter',`chip ${s.market===x?'on':''}`,`data-category="${x}"`)).join('')}</div>${!items.length && !published.length ? '<div class="empty"><h3>No apps match yet</h3><p>Try another category or search.</p></div>' : ''}<div class="market-grid">${published.map(r=>`<article class="market-card"><div class="market-art" style="--market-accent:${themeFor(r,themes).accent}"><span>${icon('bot',32)}</span></div><div><span class="hint">${esc(r.platform.marketplace.category)} · Your published app</span><h3>${esc(r.name)}</h3><p>${esc(r.platform.marketplace.summary)}</p><a class="btn sm" href="?release=${r.id}" target="_blank" rel="noopener">Open app</a></div></article>`).join('')}${items.map(x=>`<article class="market-card"><div class="market-art" style="--market-accent:${themes[x.theme]?.accent || themes.forest.accent}"><span>${icon(x.category==='Analytics'?'db':'bot',32)}</span><div class="market-lines"><i></i><i></i><i></i></div></div><div><span class="hint">${x.category} · ${x.use}</span><h3>${x.name}</h3><p>${x.summary}</p>${btn('Preview and inspect','cap-market-detail','btn sm',`data-i="${marketItems.indexOf(x)}"`)}</div></article>`).join('')}</div>`,'',{wide:true});
  }
  function marketDetail(i) {
    const x=marketItems[i];
    dialog(x.name,x.summary,`<div class="two"><div class="card market-preview"><h3>${x.category === 'Analytics' ? 'What grew this quarter?' : x.category === 'HR' ? 'How much leave can I carry over?' : 'I was charged twice'}</h3><p style="margin-top:16px">${x.category === 'Analytics' ? 'Compare regional totals and show the rows behind the answer.' : x.category === 'HR' ? 'Up to five unused days, used by March 31. Source: leave policy.' : 'Billing request · high priority. Review a draft reply before sending.'}</p><small class="hint">Illustrative preview</small></div><div class="card"><h3>How it works</h3><ol class="trace">${['User enters a request',...x.agents,'Show the result with evidence'].map(a=>`<li>${a}</li>`).join('')}</ol><details><summary>Inspect the starter prompt</summary><p style="margin-top:10px">${x.prompt}</p></details></div></div>`,btn('Back to agentlets','cap-market','btn')+btn('Customize this app','cap-market-use','btn primary',`data-i="${i}"`),{wide:true});
  }
  function promptLibrary() {
    dialog('Prompt library','Pick a starting point, then make it specific to your team.',`<div class="stack">${marketItems.map((x,i)=>btn(`<span class="grow"><b>${x.use}</b><small>${x.prompt}</small></span>${icon('arrow',15)}`,'cap-prompt-edit','choice',`data-i="${i}"`)).join('')}</div>`);
  }
  function designDialog() {
    const presets=Object.entries(themes).map(([id,t])=>({id,name:t.label,theme:id,tokens:t,scope:'Preset'}));
    db().designSystems ||= [];
    const all=[...presets,...db().designSystems];
    const current=all.find(x=>x.id===s.selectedTheme) || all.find(x=>x.id===project()?.platform?.design?.id) || all[0];
    s.selectedTheme=current.id;
    const t=current.tokens;
    dialog('Design systems','Preview a preset or save a reusable palette for yourself or your organization.',`<div class="design-layout"><div><div class="row wrap">${['All','Preset','Personal','Organization'].map(k=>btn(k,'cap-design-scope',`chip ${s.designScope===k?'on':''}`,`data-scope="${k}"`)).join('')}</div><div class="theme-list">${all.filter(x=>s.designScope==='All'||x.scope===s.designScope).map(x=>btn(`<span class="palette">${[x.tokens.bg,x.tokens.ink,x.tokens.accent].map(c=>`<i style="background:${c}"></i>`).join('')}</span><span class="grow"><b>${esc(x.name)}</b><small>${x.scope}</small></span>${x.id===current.id?icon('check',15):''}`,'cap-design-pick',`choice ${x.id===current.id?'selected':''}`,`data-id="${x.id}"`)).join('') || '<p class="muted">No saved systems here yet. Create one below.</p>'}</div>${btn('Create design system','cap-design-new','btn')}${current.scope !== 'Preset' ? btn('Edit selected','cap-design-edit','btn',`data-id="${current.id}"`) : ''}</div><div class="design-preview" style="background:${t.bg};color:${t.ink};--design-accent:${t.accent}"><span>App preview</span><h3>${esc(project()?.name || 'Your next app')}</h3><p>Clear answers, grounded in your knowledge.</p><div style="background:${t.surface};border:1px solid ${t.line}"><b>What can I help you with?</b><p style="color:${t.muted}">Ask a question and see where the answer comes from.</p><span style="display:inline-block;padding:8px 16px;border-radius:22px;background:${t.accent};color:${t.onAccent}">Ask a question</span></div><p class="hint">${esc(current.name)} · DM Sans</p></div></div>`,btn(project()?'Apply to this app':'Use for next app','cap-design-apply','btn primary'),{wide:true});
  }
  function publishing() {
    const p=project(), st=platform(p), m=st.marketplace;
    dialog('Publishing settings','Manage discovery and measurement alongside your releases.',form('publishing',`${check('cap-analytics','Record app usage in this browser',st.analytics)}${check('cap-listing','List this app in the example marketplace',m.enabled)}${select('cap-category','Category',['Productivity','HR','Support','Analytics','Finance','Marketing'],m.category)}${field('cap-summary','Short description',m.summary,'maxlength="160"')}<label class="field-label" for="cap-description">Description</label><textarea id="cap-description" rows="4">${esc(m.description)}</textarea>${field('cap-tags','Tags (up to 8, separated by commas)',m.tags.join(', '))}<p class="hint">Listing is simulated. The saved card is visible here; it is not submitted to Lyzr’s marketplace.</p>`,'Save publishing settings'),btn('View analytics','cap-analytics','btn sm')+(m.enabled?btn('Preview listing','cap-listing-preview','btn sm'):''),{wide:true});
  }
  function analytics() {
    const p=project(), events=p.events || [], runs=p.runs || [];
    const feedback=events.filter(e=>e.type==='feedback'), asks=events.filter(e=>e.type==='question');
    const answered=asks.filter(e=>e.supported).length;
    dialog('App analytics','Activity recorded in this browser. Preview tests are separated from released-app usage.',`<div class="stats-grid">${[[asks.length,'Released-app questions'],[asks.length?`${Math.round(answered/asks.length*100)}%`:'—','Questions answered'],[feedback.length,'Feedback responses'],[runs.length,'Preview and agent tests']].map(([n,l])=>`<div><strong>${n}</strong><span>${l}</span></div>`).join('')}</div><div class="card"><div class="row between"><h3>Recent activity</h3><span class="status">${platform(p).analytics?'Recording enabled':'Recording paused'}</span></div>${events.length ? [...events].reverse().slice(0,12).map(e=>`<div class="listrow"><span>${esc(e.type === 'question' ? e.supported ? 'Question answered' : 'Question needed a handoff' : e.type==='feedback' ? `Feedback: ${e.value}` : e.type)}</span><small>${new Date(e.at).toLocaleString()}</small></div>`).join('') : '<div class="empty"><h3>No released-app activity yet</h3><p>Publish the app, open its release in this browser and ask a question.</p></div>'}</div>`,btn('Publishing settings','cap-publishing','btn'),{wide:true});
  }
  function authPreview(expired=false, signup=false) {
    const st=platform(project());
    dialog(expired?'Your session expired':signup?'Create your app account':`Sign in to ${esc(project().name)}`,expired?'Sign in again to return to the app. Your work is preserved.':'Demo access flow. No password or provider account is needed.',`<div class="card stack"><p>${esc(st.auth.provider)} sign-in</p>${btn(`Continue with demo ${st.auth.provider} account`,'cap-auth-complete','btn primary')}${st.auth.signup && !signup ? btn('Create an account','cap-auth-signup','link'):''}</div>`);
  }
  Object.assign(act, {
    'cap-data': el=>{s.data=el.dataset.view;ui.tab='data';ui.mobile='app';render();},
    'cap-collection': el=>{s.collection=el.dataset.name;s.query='';render();},
    'cap-collection-new':()=>collectionForm(), 'cap-schema-edit':()=>collectionForm(true),
    'cap-schema-toggle':()=>{s.schema=!s.schema;render();},
    'cap-record-new':()=>recordForm(), 'cap-record-edit':el=>recordForm(el.dataset.id),
    'cap-record-delete':el=>dialog('Delete this record?','You can recover it by restoring the version before this change.','',btn('Keep record','close')+btn('Delete record','cap-record-delete-confirm','btn danger',`data-id="${el.dataset.id}"`)),
    'cap-record-delete-confirm':el=>{change('Deleted database record',p=>{const c=platform(p).collections.find(c=>c.name===s.collection);c.records=c.records.filter(r=>r.id!==el.dataset.id);});closeModal();render();},
    'cap-workflow':()=>{ui.agentSel='workflow';ui.tab='agents';ui.mobile='app';render();},
    'cap-node':el=>editAgent(el.dataset.id), 'cap-route-new':routeDialog,
    'cap-route-delete':el=>{change('Removed agent handoff',p=>{platform(p).routingConfigured=true;platform(p).routes=platform(p).routes.filter(r=>r.id!==el.dataset.id);});render();},
    'cap-agent-duplicate':el=>{change('Duplicated agent',p=>{const a=p.agents.find(a=>a.id===el.dataset.id);p.agents.push({...structuredClone(a),id:crypto.randomUUID(),name:a.name+' copy'});});closeModal();ui.agentSel='workflow';render();},
    'cap-connections':connections,'cap-connection-new':el=>connectionForm(el.dataset.kind),'cap-connection-edit':el=>connectionForm('',el.dataset.id),
    'cap-connection-test':el=>{const c=platform(project()).connections.find(c=>c.id===el.dataset.id);dialog('Connection test','Simulated contract test; no request was sent.',`<ol class="trace"><li>HTTPS endpoint format accepted</li><li>${esc(c.auth)} credential placeholder configured</li><li>${esc(c.actions.join(', '))} permitted for ${esc(agentName(c.agent))}</li><li>Resource scope: ${esc(c.scope)}</li><li>${c.approval?'Write actions wait for human approval':'Actions use the selected permissions'}</li></ol>`,btn('Back to connections','cap-connections','btn primary'));},
    'cap-connection-remove':el=>{change('Disconnected tool',p=>{platform(p).connections=platform(p).connections.filter(c=>c.id!==el.dataset.id);});connections();},
    'cap-architecture':()=>{const st=platform(project());dialog('Who owns the agents?','Choose the management path. Your app stays in the same workspace.',form('architecture',`<div class="two"><div class="card"><h3>Lyzr managed</h3><p>Configure agents here, then use Studio for deeper management. Architect handles the app-to-agent connection.</p></div><div class="card"><h3>Repository / GitAgent</h3><p>Keep prompts, tools and orchestration in Git. Review changes through branches and pull requests.</p></div></div>${select('cap-management','Management path',[['managed','Lyzr managed'],['repository','Repository / GitAgent']],st.architecture)}<p class="hint">This choice generates a workbench manifest and ownership flow. It does not migrate or run a real GitAgent.</p>`,'Save architecture'),'',{wide:true});},
    'cap-advanced':()=>{const o=platform(project()).agentOptions;dialog('Advanced agent settings','These settings are exported with the agent workflow; model execution is simulated.',form('advanced',`${check('cap-memory','Remember context within a conversation',o.memory)}${check('cap-approval','Require approval before external write actions',o.approval)}${field('cap-temperature','Temperature',o.temperature,'type="number" min="0" max="2" step="0.1" required')}<a href="https://studio.lyzr.ai/" target="_blank" rel="noopener">Open Lyzr Studio for managed agents</a>`,'Save settings'));},
    'cap-market':library,'cap-market-filter':el=>{s.market=el.dataset.category;library();},'cap-market-detail':el=>marketDetail(+el.dataset.i),
    'cap-market-use':el=>{const x=marketItems[+el.dataset.i];dialog('Customize '+x.name,'Describe your audience and context before building.',form('prompt',`<label class="field-label" for="cap-prompt-text">Your app brief</label><textarea id="cap-prompt-text" rows="5" required>${esc(x.prompt)}</textarea>`,'Build this app'));},
    'cap-prompts':promptLibrary,'cap-prompt-edit':el=>act['cap-market-use'](el),
    'cap-design':designDialog,'cap-design-scope':el=>{s.designScope=el.dataset.scope;designDialog();},'cap-design-pick':el=>{s.selectedTheme=el.dataset.id;designDialog();},
    'cap-design-edit':el=>act['cap-design-new'](el),
    'cap-design-new':el=>{const existing=db().designSystems?.find(d=>d.id===el?.dataset?.id);const t=existing?.tokens || themeFor(project() || {settings:{theme:'forest'}},themes);dialog(existing?'Edit design system':'Create a design system','Save a palette for reuse across projects. Organization sharing is a local demo.',form('design',`<input type="hidden" id="cap-design-id" value="${existing?.id || ''}">`+field('cap-design-name','Name',existing?.name || '','required placeholder="Northstar brand"')+select('cap-design-scope','Available to',['Personal','Organization'],existing?.scope || 'Personal')+field('cap-design-bg','Background',t.bg,'type="color"')+field('cap-design-ink','Text',t.ink,'type="color"')+field('cap-design-accent','Accent',t.accent,'type="color"'),'Save design system'));},
    'cap-design-apply':()=>{const preset=themes[s.selectedTheme];const saved=db().designSystems?.find(x=>x.id===s.selectedTheme);const d=saved || {id:s.selectedTheme,name:preset.label,theme:s.selectedTheme,tokens:preset,scope:'Preset'};if(project()) change('Applied design system: '+d.name,p=>{p.settings.theme=d.theme;platform(p).design=structuredClone(d);});else {db().defaultDesign=structuredClone(d);save();}closeModal();render();toast(project()?'Design system applied.':'Design system saved for your next app.');},
    'cap-publishing':publishing,'cap-analytics':analytics,
    'cap-listing-preview':()=>{const p=project(),m=platform(p).marketplace;dialog('Marketplace listing preview','Saved locally. Not submitted to an external directory.',`<article class="card"><span class="hint">${esc(m.category)}</span><h3>${esc(p.name)}</h3><p>${esc(m.summary)}</p><hr><p>${esc(m.description)}</p><p class="hint" style="margin-top:14px">${esc(m.tags.join(' · '))}</p><p class="status" style="margin-top:12px">${p.releases.at(-1)?.platform?.marketplace?.enabled && p.releases.at(-1)?.revision === p.revision ? 'Published in your local marketplace' : 'Publish this version to update your local marketplace listing'}</p></article>`,btn('Edit listing','cap-publishing','btn'));},
    'cap-auth-preview':()=>authPreview(),'cap-auth-expired':()=>authPreview(true),'cap-auth-signup':()=>authPreview(false,true),
    'cap-auth-complete':()=>dialog('You’re signed in','Demo session started. The app’s access settings determine the production journey.',`<div class="card"><strong>alex@example.com</strong><p>Session duration: ${platform(project()).auth.sessionHours} hours</p></div>`,btn('Return to app','cap-return-preview','btn primary')),
    'cap-return-preview':()=>{closeModal();ui.tab='preview';render();},
    'cap-help':()=>dialog('Help and resources','Choose a task to see the next step.',`<div class="stack"><details open><summary>Create your first app</summary><p>Describe the audience, task and desired result on Home. Use Plan first to review the plan before building. The app and agents can be changed afterward.</p></details><details><summary>Continue an existing project</summary><p>Import an example repository, resolve missing variables in Code, make a change and run tests. Review the diff and merge a PR before publishing.</p></details><details><summary>Recover a change</summary><p>Open Version history in the top bar. Restore adds a new version; release rollback also creates a new release. Database records and workflow settings are included.</p></details><details><summary>Get support</summary><p>Export your project and note the step that failed. This prototype has no support inbox.</p><a href="https://docs.lyzr.ai/enterprise/architect/build/build-guide" target="_blank" rel="noopener">Read Architect documentation</a></details></div>`,btn('Prototype boundaries','about','btn')),
    'cap-plans':()=>dialog('Plan and usage','Illustrative plan choices. No checkout or billing changes are made.',`<div class="two"><div class="card"><h3>Personal</h3><p>One workspace for your own projects, source export and app publishing.</p>${btn('Select Personal demo','cap-plan-pick','btn sm','data-plan="Personal"')}</div><div class="card"><h3>Team</h3><p>Shared projects, organization design systems and usage visibility.</p>${btn('Select Team demo','cap-plan-pick','btn sm','data-plan="Team"')}</div></div><p class="hint">Active demo plan: ${esc(db().plan || 'Team')}. Credits shown elsewhere are illustrative.</p>`,btn('View usage','usage','btn')),
    'cap-plan-pick':el=>{db().plan=el.dataset.plan;save();act['cap-plans']();toast('Demo plan updated.');},
  });
  document.addEventListener('submit', e=>{
    if (!e.target.id.startsWith('cap-')) return;
    e.preventDefault();
    try {
      const id=e.target.id;
      if(id==='cap-market-search') {s.marketQuery=val('cap-market-query');library();}
      if(id==='cap-schema') {const fields=JSON.parse(val('cap-fields')), editing=val('cap-schema-editing'), name=editing || val('cap-collection-name');change(editing?'Updated database schema':'Created collection '+name,p=>editing?saveSchema(p,name,fields):addCollection(p,name,fields));s.collection=name;closeModal();render();}
      if(id==='cap-record') {const value=JSON.parse(val('cap-record-json')),id=val('cap-record-id');change('Saved database record',p=>saveRecord(p,s.collection,value,id));closeModal();render();}
      if(id==='cap-search-records') {s.query=val('cap-record-query');render();}
      if(id==='cap-route') {const route={from:val('cap-from'),to:val('cap-to'),when:val('cap-when')};change('Connected agents',p=>saveRoute(p,route));closeModal();render();}
      if(id==='cap-workflow-test') {const p=project(),input=val('cap-workflow-input'),r=answer(p,input);recordRun(p,input,r);s.trace={input,output:r.text,nodes:workflowTrace(p,r.supported)};save();render();}
      if(id==='cap-agent') {const a={name:val('cap-agent-name'),responsibility:val('cap-agent-job'),instructions:val('cap-agent-instructions'),framework:val('cap-agent-framework'),entry:val('cap-agent-entry'),enabled:checked('cap-agent-enabled')},agentId=val('cap-agent-id');change('Updated agent '+a.name,p=>Object.assign(p.agents.find(x=>x.id===agentId),a));closeModal();ui.agentSel='workflow';render();}
      if(id==='cap-connection') {const c={id:val('cap-connection-id')||crypto.randomUUID(),kind:val('cap-connection-kind'),name:val('cap-connection-name'),endpoint:val('cap-endpoint'),scope:val('cap-scope'),agent:val('cap-connection-agent'),auth:val('cap-connection-auth'),env:val('cap-connection-env'),actions:['read','write','execute'].filter(a=>checked('cap-action-'+a)),approval:checked('cap-connection-approval'),status:'Configured · simulated'};validateConnection(c);change('Configured connection '+c.name,p=>{const st=platform(p);st.connections=st.connections.filter(x=>x.id!==c.id);st.connections.push(c);});connections();}
      if(id==='cap-architecture') {const v=val('cap-management');change('Changed agent ownership',p=>platform(p).architecture=v);closeModal();render();}
      if(id==='cap-advanced') {const options={memory:checked('cap-memory'),approval:checked('cap-approval'),temperature:Number(val('cap-temperature'))};change('Updated advanced agent settings',p=>platform(p).agentOptions=options);closeModal();render();}
      if(id==='cap-auth') {const auth={provider:val('cap-provider'),signup:checked('cap-signup'),sessionHours:Number(val('cap-session'))},required=checked('cap-required');change('Updated app authentication',p=>{platform(p).auth=auth;p.settings.audience=required?'team':'public';p.settings.signin=required?auth.provider:'';if(required)platform(p).marketplace.enabled=false;});render();}
      if(id==='cap-publishing') {const m={enabled:checked('cap-listing'),category:val('cap-category'),summary:val('cap-summary'),description:val('cap-description'),tags:val('cap-tags').split(',').map(x=>x.trim()).filter(Boolean)},analytics=checked('cap-analytics');validateListing(m,project().settings.audience);change('Updated publishing settings',p=>{platform(p).marketplace=m;platform(p).analytics=analytics;});publishing();}
      if(id==='cap-prompt') {const brief=val('cap-prompt-text');closeModal();if(requireAccount({type:'build',brief}))startProject(brief);}
      if(id==='cap-design') {const bg=val('cap-design-bg'),ink=val('cap-design-ink'),accent=val('cap-design-accent');const lum=hex=>{const c=hex.slice(1).match(/../g).map(v=>parseInt(v,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return .2126*c[0]+.7152*c[1]+.0722*c[2];};const ratio=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05);if(ratio(bg,ink)<4.5)throw Error('Text and background need at least 4.5:1 contrast. Choose a darker text color or lighter background.');const d={id:val('cap-design-id') || crypto.randomUUID(),name:val('cap-design-name'),scope:val('cap-design-scope'),theme:project()?.settings.theme||'forest',tokens:{...themes.forest,bg,ink,accent,onAccent:ratio(accent,'#ffffff')>=ratio(accent,'#000000')?'#ffffff':'#000000'}};db().designSystems ||= [];db().designSystems=db().designSystems.filter(x=>x.id!==d.id);db().designSystems.push(d);s.selectedTheme=d.id;save();designDialog();}
    } catch(error) {const el=e.target.querySelector('#cap-error');if(el)el.textContent=error instanceof SyntaxError?'Enter valid JSON. Check quotes, commas and brackets.':error.message;else toast(error.message);}
  });
  return { s, dataPane, navData, workflowPane };
}
